// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvn4knD1GJnNT-t_YIxGDM2229NRt-Eg8',
    appId: '1:573507791860:web:b6582dbf45929722e8e7a1',
    messagingSenderId: '573507791860',
    projectId: 'zeyarah-backend',
    authDomain: 'zeyarah-backend.firebaseapp.com',
    storageBucket: 'zeyarah-backend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyBxxjLH40g83mpeb2jBnRd-4YHJa_domes',
      appId: '1:573507791860:android:c68704b9db9dc85de8e7a1',
      messagingSenderId: '573507791860',
      projectId: 'zeyarah-backend',
      storageBucket: 'zeyarah-backend.appspot.com',
      androidClientId:
          '573507791860-51sjd86bnl9rifs93ds2ifl785ujobk3.apps.googleusercontent.com');

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfV7_9aOLsCPvL6MvgkFm0g6MfSqEdNCE',
    appId: '1:573507791860:ios:26f2b3768f77612fe8e7a1',
    messagingSenderId: '573507791860',
    projectId: 'zeyarah-backend',
    storageBucket: 'zeyarah-backend.appspot.com',
    iosClientId:
        '573507791860-40fl91rdje01dr8b7opvu9g0jcn5ihbk.apps.googleusercontent.com',
    iosBundleId: 'link.ahmedsalem.zeyarah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfV7_9aOLsCPvL6MvgkFm0g6MfSqEdNCE',
    appId: '1:573507791860:ios:26f2b3768f77612fe8e7a1',
    messagingSenderId: '573507791860',
    projectId: 'zeyarah-backend',
    storageBucket: 'zeyarah-backend.appspot.com',
    iosClientId:
        '573507791860-40fl91rdje01dr8b7opvu9g0jcn5ihbk.apps.googleusercontent.com',
    iosBundleId: 'link.ahmedsalem.zeyarah',
  );
}
